export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_DEVICES_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_DEVICES_SUCCESS';
export const GET_ALL_BOOKS_ERROR = 'GET_ALL_DEVICES_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_FALIURE';
export const LOGIN_CLEAN = 'LOGIN_CLEAN'


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';